---
- hosts: devops
  remote_user: ubuntu
  become: true

  tasks:
          - name: Install Apache webserver
            apt:
                    name: apache2
                    state: present
          - name: Enable Apache webserver service
            service:
                    name: apache2
                    enabled: yes
          - name: Install mysql
            apt:
                    name: mysql-server
                    update_cache: yes
                    cache_valid_time: 3600
                    state: present
          - name: Enable mysql
            service:
                    name: mysql
                    enabled: yes
          - name: Install telnet
            apt:
                    name: telnet
                    state: present
          - name: Install curl
            apt:
                    name: curl
                    state: present

          - name: Disable UFW
            ufw:
                    state: disabled

          - name: Install nslookup
            apt:
                    name: dnsutils
                    state: present
          - name: Install add-apt-repostory
            become: yes
            apt: name=software-properties-common state=latest
          
          - name: ensure the apt repository key is present
            apt_key:
                    id: EA8CACC073C3DB2A
                    keyserver: hkp://keyserver.ubuntu.com:80
                    state: present
          
          - name: Add Oracle Java Repository
            become: yes
            apt_repository:
                    repo: deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main
                    state: present
                    update_cache: yes
          
          - name: Accept Java12 License
            become: yes
            debconf: name='oracle-java12-installer' question='shared/accepted-oracle-license-v1-2' value='true' vtype='select'

          - name: Install Oracle Java 12
            become: yes
            apt: 
                name: [ca-certificates,oracle-java12-installer,oracle-java12-set-default]
                state: present 
          
          - name: create /opt/tomcat directory
            file:
                path: /opt/tomcat
                state: directory
                mode: 0755

          - name: download and unarchive
            unarchive:
                src: https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.22/bin/apache-tomcat-9.0.22.tar.gz
                dest: /opt/tomcat
                remote_src: yes
                extra_opts: [--strip-components=1]

          - name: add tomcat group
            group:
                name: tomcat

          - name: add tomcat user
            user:
                name: tomcat
                group: tomcat
                home: /usr/share/tomcat
                createhome: no

          - name: Change ownership
            file:
                path: /opt/tomcat
                owner: tomcat
                group: tomcat
                mode: 0755
                recurse: yes
                state: directory

          - name: Copy Tomcat service from local to remote
            copy:
                src: tomcat.service
                dest: /etc/systemd/system/
                mode: 0755

          - name: Start and enable Tomcat service
            systemd:
                name: tomcat
                state: started
                enabled: true
                daemon_reload: true
